spring:
  application:
    name: eureka-client-web
  output:
    ansi:
      enabled: ALWAYS
server:
  context-path: /web
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://10.211.55.11:8761/eureka/,http://10.211.55.12:8761/eureka/