profile: node1
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl: 
       defaultZone: http://10.211.55.12:8761/eureka/