profile: 8081
server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://10.211.55.11:8761/eureka/,http://10.211.55.12:8761/eureka/